baseURL = "https://exitbowie.github.io/Blog/"
languageCode = "ja"
title = "みざらし紀行"
theme = "hugo-pacman-theme"
publishDir = "docs"
paginate = 10
pygmentsUseClasses = true

[Author]
  Name = "ExitBowie"

[outputs]
  home = [ "RSS", "HTML" ]
    
[outputFormats] 
  [outputFormats.RSS]
    mediatype = "application/rss"

[Params]
  AuthorHomepage = "https://exitbowie.github.io/Blog/"
  BottomIntroduce = "電通大にいるミドリムシ<br/> Introduce2"
  Description = "ブログです"
  Subtitle = "いつまでも未晒しでありたい..."
  Twitter = "ExitBowie"
  GitHub = "ExitBowie"
  Imglogo = "img/logo.svg"
  AuthorImg = "image/Exit.jpg"
  DateFormat = "2006年01月02日"
  MonthFormat = "2006年01月"
  FancyBox = false

  [Params.GoogleAnalytics]
    ID = "UA-10147768-2"

  [Params.Disqus]
    ShortName = "Exit"

  [Params.Strings]
    Search = "Search"
    ShowSideBar = "バー"
    Categories = "カテゴリ"
    Tags = "タグ"
    TagCloud = "Tag"
    Rss = "RSS"
    TableOfContents = "目次"

[Menu]
  [[Menu.Main]]
    Name = "home"
    URL = "/"
    Weight = 1
  [[Menu.Main]]
    Name = "about"
    URL = "/about"
    Weight = 2
