baseURL = "https://exitbowie.github.io/Blog/"
languageCode = "ja"
title = "未ざらし紀行"
theme = "hugo-pacman-theme"
publishDir = "docs"
paginate = 10
pygmentsUseClasses = true
pygmentsStyle = "default"
HasCJKLanguage = true

[Author]
  Name = "ExitBowie"

[outputs]
  home = [ "RSS", "HTML" ]
    
[outputFormats] 
  [outputFormats.RSS]
    mediatype = "application/rss"

[Params]
  AuthorHomepage = "https://exitbowie.github.io/Blog/"
  BottomIntroduce = "電通大にいるミドリムシ<br/>"
  Description = "多分ブログです"
  Subtitle = "いつまでも未晒しでありたい..."
  Twitter = "ExitBowie"
  GitHub = "ExitBowie"
  Imglogo = "image/Euglena.png"
  AuthorImg = "image/Exit.jpg"
  DateFormat = "2006年01月02日"
  MonthFormat = "2006年01月"
  FancyBox = true

  [Params.GoogleAnalytics]
    ID = "UA-10147768-2"

  [Params.Disqus]
    ShortName = "Exit"

  [Params.Strings]
    Search = "Search"
    Categories = "カテゴリ"
    Tags = "タグ"
    TagCloud = "Tag Cloud"
    Rss = "RSS"
    TableOfContents = "目次"

[Menu]
  [[Menu.Main]]
    Name = "home"
    URL = "/"
    Weight = 1
  [[Menu.Main]]
    Name = "about"
    URL = "/about"
    Weight = 2
  [[Menu.Main]]
    Name = "投稿"
    URL = "/post"
    Weight = 2

